version: '2'
services:
   lineageos:
      build:
         context: ./build/docker-lineageos
         dockerfile: Dockerfile
         args:
            username: "sydent"
      image: lineageos:latest

